tweak configure and Makefile to make them usable outside focalize

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,180 +1,128 @@
 #!/bin/sh
 
-#**********************************************************************#
-#                                                                      #
-#                        FoCaLiZe compiler                             #
-#                                                                      #
-#            François Pessaux                                          #
-#            Pierre Weis                                               #
-#            Damien Doligez                                            #
-#                                                                      #
-#                               LIP6  --  INRIA Rocquencourt           #
-#                                                                      #
-#  Copyright 2008 INRIA                                                #
-#  Distributed only by permission.                                     #
-#                                                                      #
-#**********************************************************************#
+#  Copyright 2004 INRIA
+#  $Id: configure,v 1.29 2008-12-05 15:23:08 doligez Exp $
 
-# $Id: configure,v 1.74 2012-10-16 11:08:38 pessaux Exp $
-
-BOLDTAG="\033[1m"
-UNDERLINETAG="\033[4m"
-NORMALTAG="\033[0m"
-
-touch .depend
-
-# First recover the configuration file providing the name of ocaml and coq commands.
-if [ -f "../.config_var" ] ;
-    then
-    source ../.config_var
-else
-    echo "Error.Global configuration file not found."
-    echo "Run ./configure from the parent directory."
-    exit 1
-fi
-
-# Look for a hash command.
-check_command () {
+check () {
   type "$1" >/dev/null 2>&1
 }
 
-SUM_COMMAND=""
+# Default settings
+PREFIX=/usr/local
+DEBUG=false
+
+SUM=:
+CONVERT=:
+COQC=:
+GS=:
+
+BYT_DEBUG_FLAGS=
+BIN_DEBUG_FLAGS=
+
+if ocamlc.opt -v >/dev/null; then
+  OCAMLC=ocamlc.opt
+elif ocamlc -v >/dev/null; then
+  OCAMLC=ocamlc
+else
+  echo 'Cannot find ocamlc[.opt] compiler in path' >&2
+  exit 2
+fi
+
+if ocamlopt.opt -v >/dev/null; then
+  OCAMLOPT=ocamlopt.opt
+elif ocamlopt -v >/dev/null; then
+  OCAMLOPT=ocamlopt
+else
+  echo 'Cannot find ocamlopt[.opt] compiler in path' >&2
+  exit 2
+fi
+
+BIN_DIR="${PREFIX}/bin"
+LIB_DIR="${PREFIX}/lib"
+
+if check convert; then CONVERT=convert; else CONVERT=:; fi
+if check coqc; then COQC=coqc; else COQC=:; fi
+if check coqdep; then COQDEP=coqdep; else COQDEP=:; fi
+if check gs; then GS=gs; else GS=:; fi
+
 for i in sum md5 md5sum md5deep sha1deep sha256deep; do
-  if check_command $i ; then SUM_COMMAND=$i ; break ; fi
+  if check $i; then SUM=$i; break; fi
 done
 
+if check cygpath; then EXE=.exe; else EXE=""; fi
 
-# Remembering the number of arguments to this script, in order
-# to parse them properly.
-argc="$#"
+while : ; do
+  case $# in 0) break;; esac
+  case "$1" in
+    -prefix | --prefix) BIN_DIR="$2/bin"; LIB_DIR="$2/lib"; shift 2;;
+    -bindir | --bindir) BIN_DIR="$2"; shift 2;;
+    -libdir | --libdir) LIB_DIR="$2"; shift 2;;
+    -convert | --convert) CONVERT="$2"; shift 2;;
+    -coqc | --coqc) COQC="$2"; shift 2;;
+    -debug | --debug | -enable-debug | --enable-debug) DEBUG=true; shift;;
+    -gs | --gs) GS="$2"; shift 2;;
+    -nodebug | --nodebug | -disable-debug | --disable-debug)
+       DEBUG=false; shift;;
+    -suffix | --suffix) EXE="$2"; shift 2;;
+    -sum | --sum) SUM="$2"; shift 2;;
+    -help | --help)
+       echo "usage: ./configure [options]"
+       echo "options are:"
+       echo "  [-]-bindir <directory>"
+       echo "    set install directory for executables (default ${BIN_DIR})"
+       echo "  [-]-convert <executable-file>"
+       echo "    set absolute path for the \"convert\" command."
+       echo "  [-]-coq <executable-file>"
+       echo "    set absolute path for the \"coqc\" command."
+       echo "  [-]-debug | [-]-enable-debug"
+       echo "    enable debugging"
+       echo "  [-]-nodebug | [-]-disable-debug"
+       echo "    disable debugging (default)"
+       echo "  [-]-exe <suffix>"
+       echo "    set suffix for executable files"
+       echo "  [-]-gs <executable-file>"
+       echo "    set absolute path for the \"gs\" command."
+       echo "  [-]-libdir <directory>"
+       echo "    set install directory for libraries (default ${LIB_DIR})"
+       echo "  [-]-prefix <directory>"
+       echo "    set prefix for install directories (default ${PREFIX})"
+       echo "  [-]-sum <executable-file>"
+       echo "    set absolute path for the \"sum\" command."
+       echo "  [-]-help";
+       echo "    display this help text and exit"
+       exit 0
+       ;;
+    *) echo "./configure: bad option '$1'" >&2
+       echo "For help, use ./configure -help" >&2
+       exit 2
+       ;;
+  esac
+done
 
-INTERACTIVE=false;
-INSTALL_PREFIX_GIVEN=false;
-INSTALL_PREFIX=/usr/local
-
-
-usage () {
-    echo "usage: ./configure [options] [<directory>]"
-    echo
-    echo "Options are:"
-    echo "  [-]-install_prefix <directory>"
-    echo "    set <directory> as the directory prefix for installation of"
-    echo "    the FoCaLize commands."
-    echo "    (Default value for <directory> is $BOLDTAG$INSTALL_PREFIX$NORMALTAG.)"
-    echo "  [-]-interactive"
-    echo "    run interactively, asking questions."
-}
-
-
-# #############################################################################
-# Installation stuff.
-case ${argc} in
-  0) ;;
-  *)
-  while : ; do
-    # If nothing else to parse then end the loop.
-    case $# in 0) break;; *);; esac
-    case "$1" in
-      -interactive | --interactive)
-       INTERACTIVE=true;
-       shift;;
-      -install_prefix | --install_prefix)
-       INSTALL_PREFIX_GIVEN=true;
-       INSTALL_PREFIX="$2";
-       shift 2;;
-      -help | --help)
-       usage;
-       shift;
-       exit 0;;
-      -*)
-       option="$1";
-       echo "./configure: bad option '${option}'" >&2 && \
-       echo "For help, use ./configure -help" >&2 && \
-       shift;
-       exit 2;;
-    esac;
-  done
-  ;;
-esac
-
-# At this point, if INSTALL_PREFIX has been overriden while parsing options,
-# both the 2 following variables will take benefit of this overriding.
-INSTALL_BIN_DIR=${INSTALL_PREFIX}/bin
-INSTALL_LIB_DIR=${INSTALL_PREFIX}/lib/zenon
-
-if [ $INSTALL_PREFIX_GIVEN != true ]
-then
-    if [ $INTERACTIVE = true ]
-    then
-        # Ask question only in interactive mode, otherwise keep default value.
-        echo $BOLDTAG"Where to install Zenon binaries ?"$NORMALTAG
-        echo "Default is $INSTALL_BIN_DIR."
-        echo "Just press enter to use default location."
-        read USER_INPUT
-        if [ "$USER_INPUT" != "" ] ;
-        then
-            INSTALL_BIN_DIR=$USER_INPUT
-        fi
-    fi
-fi
-# Else, explicit install prefix given while parsing options, keep it blindly.
-
-if [ $INSTALL_PREFIX_GIVEN != true ]
-then
-    if [ $INTERACTIVE = true ]
-    then
-        # Ask question only in interactive mode, otherwise keep default value.
-        echo $BOLDTAG"Where to install Zenon libraries ?"$NORMALTAG
-        echo "Default is $INSTALL_LIB_DIR."
-        echo "Just press enter to use default location."
-        read USER_INPUT
-        if [ "$USER_INPUT" != "" ] ;
-        then
-            INSTALL_LIB_DIR=$USER_INPUT
-        fi
-    fi
-fi
-# Else, explicit install prefix given while parsing options, keep it blindly.
-
-# Check if installation directories are writable, if so do not use sudo
-# otherwise, use it.
-SUDO=
-touch $INSTALL_BIN_DIR/writable_p
-if [ "$?" = 0 ] ;
-then
-    rm -f $INSTALL_BIN_DIR/writable_p
+if $DEBUG; then
+  BYT_DEBUG_FLAGS="-g -dtypes -warn-error A"
+  BIN_DEBUG_FLAGS="-dtypes -warn-error A"
 else
-    SUDO=sudo
+  BYT_DEBUG_FLAGS=
+  BIN_DEBUG_FLAGS=
 fi
 
-if [ "$SUDO" = "" ] ;
-then
-    touch $INSTALL_LIB_DIR/writable_p
-    if [ "$?" = 0 ]
-    then
-        rm -f $INSTALL_LIB_DIR/writable_p
-    else
-        SUDO=sudo
-    fi
-fi
+rm -f .config_var
+echo "EXE=$EXE" >> .config_var
+echo "INSTALL_BIN_DIR=$BIN_DIR" >>.config_var
+echo "INSTALL_LIB_DIR=$LIB_DIR" >>.config_var
+echo "BYT_DEBUG_FLAGS=$BYT_DEBUG_FLAGS" >>.config_var
+echo "BIN_DEBUG_FLAGS=$BIN_DEBUG_FLAGS" >>.config_var
+echo "SUM=$SUM" >>.config_var
+echo "CONVERT=$CONVERT" >>.config_var
+echo "GS=$GS" >>.config_var
+echo "CAMLBYT=$OCAMLC" >>.config_var
+echo "CAMLBIN=$OCAMLOPT" >>.config_var
+echo "CAMLLEX=ocamllex" >>.config_var
+echo "CAMLYACC=ocamlyacc" >>.config_var
+echo "CAMLDEP=ocamldep" >>.config_var
+echo "COQC=$COQC" >>.config_var
+echo "COQDEP=$COQDEP" >>.config_var
 
-
-# #############################################################################
-# Generate the installation and configuration file containing tools vars.
-CONFIGURATION_VARS_FILE=.config_var
-
-rm -f $CONFIGURATION_VARS_FILE
-echo "INSTALL_BIN_DIR=$INSTALL_BIN_DIR" >> $CONFIGURATION_VARS_FILE
-echo "INSTALL_LIB_DIR=$INSTALL_LIB_DIR" >> $CONFIGURATION_VARS_FILE
-echo "SUM=$SUM_COMMAND" >> $CONFIGURATION_VARS_FILE
-echo "SUDO=$SUDO" >> $CONFIGURATION_VARS_FILE
-chmod a-w $CONFIGURATION_VARS_FILE
-
-# #############################################################################
-# Summary feedback.
-echo "Configuration summary for Zenon:"
-echo "  binaries -> $INSTALL_BIN_DIR"
-echo "  libraries -> $INSTALL_LIB_DIR"
-echo "  checksum command: $SUM_COMMAND"
-echo "  Use sudo to install -> $SUDO"
-echo "Done."
+echo "Configuration summary for zenon:"
+cat .config_var
