Added typechecking support for axiom

diff --git a/run b/run
--- a/run
+++ b/run
@@ -45,32 +45,44 @@ ERRORS=0
 
 for f in $FILES
 do
+    echo -ne "\r\033[K\e[32m$COQS proved\e[0m /\e[38m $SOLVED solved \e[0m / \e[35m$TOTAL total\e[0m"
     TOTAL=$(($TOTAL + 1))
-    ./zenon -max-time 5s -q -k -x arith -itptp $f > /dev/null 2> /dev/null
+    ./zenon -p0 -max-time 5s -q -k -x arith -itptp $f > /dev/null 2> /dev/null
     RET=$?
     if [ $RET -eq 0 ];
     then
         SOLVED=$(($SOLVED + 1))
-        ./zenon -max-time 10s -q -odotd 30 -kall -x arith -itptp $f > $f.gv
+        ./zenon -p0 -max-time 10s -q -odotd 30 -kall -x arith -itptp $f > $f.gv
         dot -Tsvg $f.gv -o $f.svg
-        ./zenon -max-time 10s -context -ocoq -opt0 -k -x arith -itptp $f > $TEMP
-        if coqc -I ./ $TEMP; then \
+        ./zenon -p0 -max-time 10s -q -context -ocoq -opt0 -k -x arith -itptp $f > $TEMP 2> /dev/null
+        coqc -I ./ $TEMP > /dev/null 2> /dev/null
+        if [ $? -eq 0 ];
+        then
             COQS=$(($COQS + 1));
-            echo -e "[PROOF FOUND] $f \e[32m[OK]\e[0m"; \
-        else \
-            echo -e "\e[31m[PROOF FOUND] $f [KO]\e[0m"; \
-        fi;
-        rm -f $TEMP;
+            # echo -e "[PROOF FOUND] $f \e[32m[OK]\e[0m"
+        else
+            echo -e "\r\033[K\e[31m[PROOF FOUND] $f [KO]\e[0m"
+            coqc -I ./ $TEMP
+        fi
+        rm -f $TEMP
     elif [ $RET -eq 12 ] || [ $RET -eq 1 ] || [ $RET -eq 13 ];
     then
-        echo -e "\e[33m[NOT FOUND] $f \e[0m"
+        #echo -e "\e[33m[NOT FOUND] $f \e[0m"
+        :
     else
         ERRORS=$(($ERRORS + 1))
-        echo -e "\e[35m[ERROR $RET] $f \e[0m"
+        echo -e "\r\033[K\e[35m[ERROR $RET] $f \e[0m"
         ./zenon -max-time 5s -k -x arith -itptp $f
     fi
 done
-echo "$COQS proved / $SOLVED solved / $TOTAL total ($ERRORS unknow errors)"
+echo -e "\r\033[K-----------------------------------"
+echo -ne "\e[32m$COQS proved\e[0m /\e[38m $SOLVED solved\e[0m / \e[35m$TOTAL total\e[0m"
+if [ $ERRORS -eq 0 ];
+then
+    echo ""
+else
+    echo -e "\e[31m($ERRORS unknow errors)\e[0m"
+fi
 
 # Clean temporary files
 rm -f $TEMP
